### ISSUE TITLE
I guess there is some problem in loading the dataset because getParam is not able to open the images even though using right path in kitti_param.yaml file

### ISSUE THREAD

**Issue by ujasmandavia** [shangzhouye/stereo-visual-slam#1]

**Comment by ujasmandavia** [comment]
started roslaunch server http://robo-ninja:46161/

SUMMARY
========

PARAMETERS
 * /dataset: /home/ujasmandavi...
 * /if_rviz: True
 * /if_write_pose: True
 * /rosdistro: melodic
 * /rosversion: 1.14.5

NODES
  /
    run_vslam (stereo_visual_slam_main/run_vslam)
    rviz (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[run_vslam-1]: started with pid [29022]
process[rviz-2]: started with pid [29023]
Could not open or find the image
Could not open or find the image
Could not open or find the image
Could not open or find the image
OpenCV Error: Assertion failed (npoints >= 4 && npoints == std::max(ipoints.checkVector(2, 5), ipoints.checkVector(2, 6))) in solvePnPRansac, file /home/ujasmandavia/opencv/modules/calib3d/src/solvepnp.cpp, line 252
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/ujasmandavia/opencv/modules/calib3d/src/solvepnp.cpp:252: error: (-215) npoints >= 4 && npoints == std::max(ipoints.checkVector(2, 5), ipoints.checkVector(2, 6)) in function solvePnPRansac

[run_vslam-1] process has died [pid 29022, exit code -6, cmd /home/ujasmandavia/catkin_ws/devel/lib/stereo_visual_slam_main/run_vslam __name:=run_vslam __log:=/home/ujasmandavia/.ros/log/642c65a6-90a0-11ea-b0f5-0026c65087b8/run_vslam-1.log].
log file: /home/ujasmandavia/.ros/log/642c65a6-90a0-11ea-b0f5-0026c65087b8/run_vslam-1*.log


Rviz is failing since its not able to load those images

**Comment by shangzhouye** [comment]
What is the path you put in `config.yaml`?

**Comment by ujasmandavia** [comment]
'/home/ujasmandavia/KITTI_Dataset/00/'. as per on my computer

**Comment by ujasmandavia** [comment]
I guess found the issue as I am missing the slash '/' behind 00 to go inside and read left and right images

**Comment by ujasmandavia** [comment]
Though you have got pretty good starting code and I'm planning to work more on backend optimization and loop closure to it

**Comment by shangzhouye** [comment]
That would be cool! Currently, it does not have a loop closure module and the tracking module and the optimization module are running in serial. I'm also planning on exploring those when I have time.
